### ISSUE TITLE
[Suggestion] Be able to preview cape with the elytra in it

### ISSUE THREAD

**Issue by barraIhsan** [rkkoszewski/minecraft-css-3d-skin-viewer#1]
So when i put this image
![BarraIhsan](https://user-images.githubusercontent.com/57800056/111725210-4392cc80-8899-11eb-9e1a-ea77366dcd56.png)
Then it will broke, pls support this format, because I think its the default format

**Comment by OliverGronowski** [comment]
I made a short step-by-step guide how to convert the default format to a working one
https://youtu.be/VHDhHCIFFdc

**Comment by rkkoszewski** [comment]
Will give it a shot when I find a bit of free time.

**Comment by rkkoszewski** [comment]
@barraIhsan This was actually already supported. I might try to update the notes to make it more clear, but to be able to use the new modern Cape just remove the "legacy" class from the Cape viewer or remove "legacy-cape" if you're using the player model viewer. 

I believe it should be possible to set this up in such a way that the legacy tag can be removed all together and support both formats without the legacy tag. But it seems very unlikely that I'll have much time to work on it, so the legacy class will have to do the job for now.
