### ISSUE TITLE
How to make a skin for Alex

### ISSUE THREAD

**Issue by smalloff** [rkkoszewski/minecraft-css-3d-skin-viewer#3]
His hands are 1 pixel narrower.
![skin_modern](https://user-images.githubusercontent.com/98415328/210612552-80639fe2-1fcd-478d-8c04-2892a741e08b.png)

**Comment by rkkoszewski** [comment]
Seems like I forgot to add that to the documentation. But the "Alex" player model is the so called "Slim variant". Just add the class "slim" to the "skin-viewer" div.

For example:

```
..
<div id="skin-viewer" class="mc-skin-viewer-11x">
..
```

would become

```
..
<div id="skin-viewer" class="mc-skin-viewer-11x slim">
..
```
